dist: trusty
sudo: required
language: scala
before_install:
# TZ needed for Oracle driver!
- export TZ=Asia/Kamchatka
- sh -v ./travis/extractNonPublicDeps
- docker version
- sh -v travis/runcontainer.sh oracle db2
- docker ps
jdk:
  - oraclejdk9
services:
  - mysql
  - postgresql
  - docker
addons:
  postgresql: "9.4"
  apt:
    packages:
    - graphviz
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
script:
- admin/build.sh
cache:
  directories:
    - "$HOME/.sbt"
    - "$HOME/.ivy2"
